apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: techtrends
        resources: {{ toJson .Values.resources }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        livenessProbe: {{ toJson .Values.livenessProbe }}
        readinessProbe: {{ toJson .Values.readinessProbe }}
