apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
spec:
  selector:
    app: techtrends
  ports:
  - name: 4111-3111
    port: 4111
    protocol: TCP
    targetPort: 3111
  type: ClusterIP