namespace:
  name: sandbox

replicaCount: 1
image:
  repository: nohasalah/techtrends
  tag: latest
resources:
  limits:
    memory: "128Mi"
    cpu: "500m"
  requests:
    cpu: "250m"
    memory: "64Mi"
containerPort: 3111
livenessProbe:
  httpGet:
    path: /healthz
    port: 3111
readinessProbe:
  httpGet:
    path: /healthz
    port: 3111

service:
  port: 4111
  protocol: TCP
  targetPort: 3111
  type: ClusterIP
