name: TechTrends - Package with Docker
on:
  push:
    branches:
      - 'main'
jobs:
  docker-build-techtrends:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout current workspace
        uses: actions/checkout@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: nohasalah/techtrends:latest
